spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5432/rest
    username: postgres
    password: postgres
    hikari:
      schema: rest
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS rest
      connection-timeout: 10000

app:
  check-client-api-header: false
  client-api-key: 123


