spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: 12345
    password: 12345
    hikari:
      schema: app
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app
      connection-timeout: 10000

app:
  check-client-api-header: false
  client-api-key: 123


