spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: postgres
    hikari:
      schema: books
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS books
      connection-timeout: 10000
app:
  cache:
    cache-names:
      - bookByTitleAndAuthor
      - booksByCategoryName
    caches:
      bookByTitleAndAuthor:
        expiry: 10m
      booksByCategoryName:
        expiry: 10m
