spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cache
    username: postgres
    password: postgres
    hikari:
      schema: cache
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS cache
      connection-timeout: 10000
app:
  redis:
    enable: true
  integration:
    base-url: http://localhost:8082
  cache:
    cacheType: redis
    cache-names:
      - databaseEntities
      - databaseEntityByName
      - databaseEntityById
    caches:
      databaseEntities:
        expiry: 10m
      databaseEntityByName:
        expiry: 10m
      databaseEntityById:
        expiry: 10m