spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cache
    username: postgres
    password: postgres
    hikari:
      schema: cache
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS cache
      connection-timeout: 10000



app:
  integration:
    base-url: http://localhost:8082
